MeasureReport Population Table
projecttacoma/ecqm-visualizers pull request #2
Opened 2022-07-25 18:18 UTC by natjoe4

# Summary
Created a table for displaying the population results of a FHIR MeasureReport

## New Behavior
New Component!! This component can be tested using the example app and will eventually be exported for use in fqm-testify

## Code Changes
- New Component: `PopulationResultsViewer`
- New types file for created types
- New testing
- Updated example app to allow for ease of testing

# Testing Guidance
- Run `npm run check`
- Reach out to me on Slack for testing example index.ts file
- Start up the example app with `cd example` then `npm start`
- Ensure the results are as expected
- Change the passed in MeasureReport array to instead be an array of the following type: `{label: string, report: fhir4.MeasureReport}`
- Rerun example app and ensure that the Patients are correctly identified by their passed-in labels

2022-07-25 19:14 UTC, mgramigna requested changes
Great start! Some small, some large yonder vvv

2022-07-25 19:14 UTC, mgramigna commented on package.json
> +    "@types/fhir": "0.0.35",
Thoughts on moving away from `@types/fhir` in this repo in favor of https://github.com/fhir-typescript/fhir-typescript? I had Sakhi do this in [this comment](https://github.com/projecttacoma/deqm-test-server-frontend/pull/2#discussion_r908732053). We can just use the `fhirJson` export and it'll behave exactly the same as `@types/fhir`.

One reason for asking for this is to not have dev/dependency issues. typescript fhir should be installed into dependencies, not dev dependencies, since it'll be explicitly imported into the component(s)

2022-07-25 19:14 UTC, mgramigna commented on src/components/PopulationResultsViewer.tsx
> +    (e: any) =>
```suggestion
function isDetailedMeasureReportArr(
  mrInfoArr: any[]
): mrInfoArr is DetailedMeasureReport[] {
  return mrInfoArr.every(
    (e) =>
```

2022-07-25 19:14 UTC, mgramigna commented on src/components/PopulationResultsViewer.tsx
> +  return mrInfoArr.every((e: any) => e.resourceType === 'MeasureReport');
```suggestion
  mrInfoArr: any[]
): mrInfoArr is fhir4.MeasureReport[] {
  return mrInfoArr.every((e) => e.resourceType === 'MeasureReport');
```

2022-07-25 19:14 UTC, mgramigna commented on test/fixtures/measureReports.json
> +[
For simplicity, in these measure report fixtures, can we get rid of stuff that isn't super relevant for unit testing that takes up a lot of space? Like removing the contained resources (SDEs), and the text.div? That way the fixtures are a bit easier to read for the unit tests

2022-07-25 19:14 UTC, mgramigna commented on package.json
> +    "@types/fhir": "0.0.35",
Thoughts on moving to https://github.com/fhir-typescript/fhir-typescript instead? That way we can install it as a true `dependency` not a dev dependency, and just replace all uses of `fhir4.*` with `fhirJson.*` (and an `import { fhirJson } from "@fhir-typescript/r4-core"`)

Might as well get ahead of the story when we have the option.

2022-07-25 19:14 UTC, mgramigna commented on src/components/PopulationResultsViewer.tsx
> +          <th>Denominator Exclusion</th>
Technically, these populations should not be hardcoded. We should be pulling off the populations from the groups within the measure report. Certain measures use different populations than these 4.

We should assemble the `th`s by looping through the group and grabbing the code.coding.code. Maybe we should prefer code.coding.display if defined, and if not fall back to code.coding.code

2022-07-25 19:14 UTC, mgramigna commented on src/components/PopulationResultsViewer.tsx
> +    </tr>
hmmmmmmmmmm

I'm thinking. Wanna get the other comments out there tho.

2022-07-25 19:22 UTC, mgramigna commented
Other suggestions:

Can you update the source code such that the component is actually exported from the library? Here's the convention:

1. Add an `index.ts` in the `components` directory that does a named export of the default export form the component:


```
// src/components/index.ts

export { default as WhateverYouWantItCalled } from './PopulationResultsViewer'
/* will add other exports here when we have other components */
```

2. Let's change the boilerplate `src/index.tsx` which we don't need anymore to a tried and true `index.ts` that for now just `export`s `*` from `./components`

---

Bootstrapping off of that, can you update the example to actually use the component? I think it's fine to commit a working example to the example directory that shows off the table. If the above exports were written right, we should be able to do `import { WhateverYouWantItCalled } from '../.';`. Maybe we can use the same measure reports that you used in test fixtures as the prop for rendering the example?

2022-07-25 21:41 UTC, natjoe4 commented on src/components/PopulationResultsViewer.tsx
> +    (e: any) =>
I get implicit any errors on these :/ Want me to disable?

2022-07-26 14:16 UTC, mgramigna commented on src/components/PopulationResultsViewer.tsx
> +    (e: any) =>
![image](https://user-images.githubusercontent.com/16297930/181028232-c34d31a9-bc67-4230-8102-91ec6380185d.png)

2022-07-26 18:39 UTC, mgramigna requested changes
Last comment: can we also export * from the `types` directory in `index.ts`? I can see a world where we might want to construct things of those types as individual variables, so we should err on the side of allowing consumers of these components to have as much access to interfaces and types as possibel

2022-07-26 18:52 UTC, mgramigna approved these changes

2022-07-26 18:52 UTC, merged